### ISSUE TITLE
Way to check app level certificates?

### ISSUE THREAD

**Issue by MegaTruckMike** [PKISolutions/SSLVerifier.WPF#9]
The application now works amazing to do webserver cert checking.  However I am also looking for a way to check app level certificates.  I know the port the apps are running on.  So is there a way to configure non HTTPS to check apps that use certs?  Or any recommendations on other applications that would do this.

thanks a bunch.

**Comment by Crypt32** [comment]
No, there is no general way to test non-TLS apps since all they implement custom protocol which is not known to our tool. If apps implement standard TLS handshake protocol, then you just type host name and port and fire check. For example, you can use this trick to test for RDS certificates, because RDP implements standard TLS negotiation flow. Just try it. If it works, then ok, you can use this tool, if not -- then we are sorry, it is out of our control.

**Comment by MegaTruckMike** [comment]
no worries.  thank you for the explanation.

m

**Comment by MegaTruckMike** [comment]
that answers that.. 

thanks again.
